version: '3.8'
services:
  app:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userform_db
      SPRING_DATASOURCE_USERNAME: userform_user
      SPRING_DATASOURCE_PASSWORD: userform_pass

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: userform_db
      MYSQL_USER: userform_user
      MYSQL_PASSWORD: userform_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
