spring:
  datasource:
    url: jdbc:mysql://mysql:3306/userform_db
    username: userform_user
    password: userform_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
server:
  port: 3333
